# Generated by Django 5.1.15 on 2026-06-29 11:25

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('is_published', models.BooleanField(default=False, help_text='Only published palettes appear in the public API.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('key', models.CharField(help_text='Token name, e.g. color.primary or space.md', max_length=100)),
                ('value', models.CharField(help_text='Token value, e.g. #2563EB or 16px', max_length=200)),
                ('palette', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='catalog.palette')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('palette', 'key'), name='unique_token_key_per_palette')],
            },
        ),
    ]
