# Generated by Django 5.1.15 on 2026-06-29 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UIKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'UI kit',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Compatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('full', 'Full'), ('partial', 'Partial'), ('none', 'None')], default='partial', max_length=20)),
                ('rationale', models.TextField(blank=True)),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='compat.stack')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='compat.uikit')),
            ],
            options={
                'verbose_name_plural': 'compatibilities',
                'ordering': ['stack__name', 'kit__name'],
                'constraints': [models.UniqueConstraint(fields=('stack', 'kit'), name='unique_stack_kit_pair')],
            },
        ),
    ]
